project:
  type: website
  output-dir: C:/Users/wujiaju.stu/Documents/GitHub/E-Portfolio

website:
  title: "Jiaju's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: capstone.qmd
        text: Capstone Project
      - href: content.qmd
        text: Skills & Deliverables
### adding new by
      #- href: contact.qmd # create this within the same file
      # text: contact information
  page-footer:
    left: "© Jiaju — MGEM e-portfolio"
    right:
      - icon: envelope-at
        href: mailto:wujiaju@student.ubc.ca
        aria-label: Email
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

